'use client';
import Navbar from '../components/Navbar'
import '../styles/globals.css'
import { AuthContextProvider } from '../contexts/auth/AuthContext'

import { Inter } from "next/font/google";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthContextProvider>
          <Navbar />
          {children}
        </AuthContextProvider>
      </body>
    </html>
  )
}
